{{- if .Values.conf.createSecrets }}
{{- if .Values.global.onPremEnabled }}
#  Copyright 2023 Google LLC
#  Copyright 2023 EPAM
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

{{- $airflowLogUserPassword := (randAlphaNum 16)}}
{{- $dagUserPassword := (randAlphaNum 16)}}
---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  {{- if .Values.minio.enabled }}
  MINIO_AIRFLOWLOG_PASSWORD: {{ $airflowLogUserPassword | b64enc | quote }}
  MINIO_ENDPOINT: {{ print "http://minio:9000" | b64enc | quote}}
  MINIO_ACCESS_KEY: {{ print "dagUser" | b64enc | quote }}
  MINIO_SECRET_KEY: {{ $dagUserPassword | b64enc | quote }}
  {{- end }}
  {{- if .Values.bootstrap.minio.external }}
  MINIO_AIRFLOWLOG_PASSWORD: {{ .Values.bootstrap.minio.airflow.password | b64enc | quote }}
  MINIO_ENDPOINT: {{ .Values.bootstrap.minio.api_url | b64enc | quote}}
  MINIO_ACCESS_KEY: {{ .Values.bootstrap.minio.dag.user | b64enc | quote }}
  MINIO_SECRET_KEY: {{ .Values.bootstrap.minio.dag.password | b64enc | quote }}
  {{- end }}
  KEYCLOAK_CLIENT_ID: {{ print "airflow" | b64enc | quote }}
  KEYCLOAK_CLIENT_SECRET: {{ randAlphaNum 16 | b64enc | quote }}
  AIRFLOW_USER: {{ .Values.airflow.auth.username | b64enc | quote }}
  AIRFLOW_PASSWORD: {{ .Values.airflow.auth.password | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-database-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  # may not work with external host properly
  AIRFLOW_DATABASE_HOST: {{ .Values.postgresql.fullnameOverride | b64enc | quote }}
  AIRFLOW_DATABASE_PORT_NUMBER: {{ .Values.bootstrap.postgres.secret.postgresqlPort | b64enc | quote }}
  AIRFLOW_DATABASE_NAME: {{ .Values.airflow.externalDatabase.database | b64enc | quote }}
  AIRFLOW_DATABASE_USERNAME: {{ .Values.airflow.externalDatabase.user | b64enc | quote }}
  AIRFLOW_DATABASE_PASSWORD: {{ .Values.airflow.externalDatabase.password | b64enc | quote }}
{{- end }}
{{- end }}
