#  Copyright 2023 Google LLC
#  Copyright 2023 EPAM
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

{{- if .Values.airflow.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dags-config
  namespace: {{ .Release.Namespace }}
data:
{{ (.Files.Glob "dags/*.py").AsConfig | indent 2 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-bootstrap
  namespace: {{ .Release.Namespace | quote }}
data:
  CSV_PARSER_IMAGE: {{ .Values.bootstrap.airflow.dagImages.csv_parser | quote }}
  SEGY_TO_VDS_IMAGE: {{ .Values.bootstrap.airflow.dagImages.open_vds | quote }}
  SEGY_TO_ZGY_IMAGE: {{ .Values.bootstrap.airflow.dagImages.segy_to_zgy | quote }}
  WITSML_PARSER_IMAGE: {{ .Values.bootstrap.airflow.dagImages.energistics | quote }}
  DATA_PARTITION_ID: {{ .Values.global.dataPartitionId | quote }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config
  namespace: {{ .Release.Namespace | quote }}
data:
  AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "False"
  AIRFLOW__API__AUTH_BACKEND: "airflow.api.auth.backend.basic_auth"
  AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER: "s3://airflow-log/logs"
  AIRFLOW__LOGGING__REMOTE_LOGGING: "True"
  AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID: "minio"
  AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
  CLOUD_PROVIDER: "baremetal"
  ENTITLEMENTS_IMPERSONATION: "True"
  CSV_PARSER_KEYCLOAK_AUTH_URL: {{ printf "http://keycloak/realms/%s" .Values.bootstrap.keycloak.secret.keycloakRealmName | quote }}
  KEYCLOAK_AUTH: "yes"
  KEYCLOAK_AUTH_URL: {{ printf "http://keycloak/realms/%s/protocol/openid-connect/token" .Values.bootstrap.keycloak.secret.keycloakRealmName | quote }}
{{- end }}
