#  Copyright 2023 Google LLC
#  Copyright 2023 EPAM
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

{{- if .Values.minio.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-config
  namespace: {{ .Release.Namespace }}
data:
  {{- if .Values.global.useHttps }}
  MINIO_BROWSER_REDIRECT_URL: "https://minio.{{ .Values.global.domain }}"
  {{- else }}
  MINIO_BROWSER_REDIRECT_URL: "http://minio.{{ .Values.global.domain }}"
  {{- end }}
  {{- if .Values.minio.useInternalServerUrl }}
  MINIO_SERVER_URL: "http://minio:9000"
  {{- else if .Values.global.useHttps }}
  MINIO_SERVER_URL: "https://s3.{{ .Values.global.domain }}"
  {{- else }}
  MINIO_SERVER_URL: "http://s3.{{ .Values.global.domain }}"
  {{- end }}
{{- end }}
