{{- if .Values.conf.createSecrets }}
{{- if .Values.global.onPremEnabled }}
#  Copyright 2023 Google LLC
#  Copyright 2023 EPAM
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

apiVersion: v1
kind: Secret
metadata:
  name: "workflow-postgres-secret"
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  {{- with .Values.bootstrap.postgres.workflow }}
  POSTGRES_DB_USERNAME_SYSTEM: {{ .user | b64enc | quote }}
  WORKFLOW_POSTGRES_DB_NAME: {{ .name | b64enc | quote }}
  {{- if $.Values.bootstrap.postgres.external }}
  WORKFLOW_POSTGRES_HOST: {{ .host | b64enc | quote }}
  WORKFLOW_POSTGRES_DB_PORT: {{ .port | b64enc | quote }}
  POSTGRES_DATASOURCE_URL_SYSTEM: {{ printf "jdbc:postgresql://%s:%s/%s" .host .port .name | b64enc | quote }}
  POSTGRES_DB_PASSWORD_SYSTEM: {{ .password | b64enc | quote }}
  {{- else }}
  POSTGRES_DATASOURCE_URL_SYSTEM: {{ printf "jdbc:postgresql://%s:%s/%s" $.Values.postgresql.fullnameOverride .port .name | b64enc | quote }}
  POSTGRES_DB_PASSWORD_SYSTEM: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
  {{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: "workflow-airflow-secret"
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  {{- if .Values.airflow.enabled }}
  OSDU_AIRFLOW_USERNAME: {{ .Values.airflow.auth.username | b64enc | quote }}
  OSDU_AIRFLOW_PASSWORD: {{ .Values.airflow.auth.password | b64enc | quote }}
  {{- else }}
  OSDU_AIRFLOW_USERNAME: {{ .Values.bootstrap.airflow.username | b64enc | quote }}
  OSDU_AIRFLOW_PASSWORD: {{ .Values.bootstrap.airflow.password | b64enc | quote }}
  {{- end }}

---
{{- if not .Values.airflow.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: "airflow"
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  airflow-password: {{ .Values.bootstrap.airflow.password | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
